server:
  port: 8081
spring:
  profiles:
    active: prod
---
server:
  port: 8082
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod


#person:
#  lastName: zhang
#  age: 18
#  boss: false
#  birth: 2017/01/01
#  maps: {k1: v1, k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: Wangcai
#    age: 2